document.writeln("<script src=\"http://sx.cnu.edu.cn/js/portal.js\" type=\"text/javascript\"></script>");	
document.writeln("<link href=\"http://sx.cnu.edu.cn/portal/sdsfdx/css/common.css\" type=\"text/css\" rel=\"stylesheet\"/>");	
document.writeln("<link href=\"http://sx.cnu.edu.cn/portal/sdsfdx/css/index.css\" type=\"text/css\" rel=\"stylesheet\"/>");	
document.writeln("<script src=\"http://sx.cnu.edu.cn/js/jquery.min.js\"></script>");	
document.writeln("<script type=\"text/javascript\" src=\"http://sx.cnu.edu.cn/portal/sdsfdx/js/jquery.jslides.js\"></script>");	
document.writeln("<input type=\"hidden\" id=\"curuserId\" value=\"\" />");	
document.writeln("<input type=\"hidden\" id=\"unitdomain\" value=\"sx.cnu.edu.cn\" />");	
document.writeln("<input type=\"hidden\" id=\"unitprefix\" value=\"sdsfdx\" />");	
document.writeln("<input type=\"hidden\" id=\"nationDESStr\" value=\"\" />");	
document.writeln("<script>");	
document.writeln("	$(function(){");	
document.writeln("		$(\".DLyh\").hover(function(){");	
document.writeln("			$(this).find(\"span\").show();");	
document.writeln("			},function(){");	
document.writeln("			$(this).find(\"span\").hide();");	
document.writeln("				})");	
document.writeln("		})");	
document.writeln("</script>");	
document.writeln("<script>");	
document.writeln("(function($, window, document, undefined) {");	
document.writeln("	/**");	
document.writeln("	 * 点击下拉显示");	
document.writeln("	 */");	
document.writeln("	$(document).on(\"click\", \".selectBox2\", function() {");	
document.writeln("		var ul = $(this).find(\"ul\"),");	
document.writeln("			display = ul.css(\"display\");");	
document.writeln("		display = display == \"block\" ? 0 : 1;");	
document.writeln("		$(\".selectBox2 ul\").css(\"display\", \"none\");");	
document.writeln("		if (display) {");	
document.writeln("			ul.css(\"display\", \"block\");");	
document.writeln("			display = 0;");	
document.writeln("			ul.find(\"li\").each(function() {");	
document.writeln("				display += $(this).height();");	
document.writeln("			});");	
document.writeln("			ul.css(\"display\", \"none\");");	
document.writeln("			if (display > 200) {");	
document.writeln("				ul.css(\"height\",200);");	
document.writeln("				ul.css(\"overflow\", \"auto\");");	
document.writeln("			}");	
document.writeln("			ul.slideDown(100);");	
document.writeln("		} else {");	
document.writeln("			ul.slideUp();");	
document.writeln("		}");	
document.writeln("		return false;");	
document.writeln("	});");	
document.writeln("	/**");	
document.writeln("	 * 点击列表 文字和 value 上去");	
document.writeln("	 */");	
document.writeln("	$(document).on(\"click\", \".selectBox2 ul li\", function() {");	
document.writeln("		var p = $(this).parent().parent().find(\"p\");");	
document.writeln("		p.text($(this).find(\"a\").text());");	
document.writeln("		p.attr(\"value\", $(this).attr(\"value\"));");	
document.writeln("		$(\"#searchTypeInp\").val($(this).attr(\"value\"));");	
document.writeln("	});");	
document.writeln("	$(document).on(\"click\", function() {");	
document.writeln("		$(\".selectBox2 ul\").slideUp();");	
document.writeln("	});");	
document.writeln("})(jQuery, window, document);");	
document.writeln("</script>");	
document.writeln("<div class=\"Header\">");	
document.writeln("	<div class=\"Headercon\">");	
document.writeln("		<div class=\"HeadLogo\">");	
document.writeln("			<a href=\"http://sx.cnu.edu.cn/portal\" >");	
document.writeln("				<img  src=\"https://p.ananas.chaoxing.com/star3/origin/a701de223bfa7715a26c5c8b41f77233.png\"    />");	
document.writeln("			</a>");	
document.writeln("		</div>");	
document.writeln("		    		<div class=\"DLbefore fr\" >");	
document.writeln("    			<dl style=\"z-index:1001;\"  class=\"DLyh\" >");	
document.writeln("    				<dt><a href=\"http://app.chaoxing.com\" target=\"_blank\"><img src=\"/portal/sdsfdx/images/khd.png\" /></a></dt>");	
document.writeln("    				<dd><a href=\"http://app.chaoxing.com\" target=\"_blank\">客户端</a></dd>");	
document.writeln("    				<span><img src=\"/portal/sdsfdx/images/ewm2.png\" /></span>");	
document.writeln("    			</dl>");	
document.writeln("    			<dl  class=\"DLyh\" >");	
document.writeln("    				<dt><a href=\"javascript:void(0)\" onclick=\"goPassport2Login();\"><img src=\"/portal/sdsfdx/images/dl.png\" /></a></dt>");	
document.writeln("    				<dd><a href=\"javascript:void(0)\" onclick=\"goPassport2Login();\">登录</a></dd>");	
document.writeln("    			</dl>");	
document.writeln("    		</div>");	
document.writeln("				<div class=\"Seacher fr\">");	
document.writeln("			<strong class=\"selectBox2\" id=\"selectBox\" onclick=\"clicked(this,event);\" style=\"display:none\">");	
document.writeln("				<p id=\"searchColumnName\">公告通知</p>");	
document.writeln("				<ul class=\"options\" style=\" display:none;\">");	
document.writeln("					<li value=\"1\"><a href=\"javascript:void(0)\" onclick=\"checkIt(this);\">公告通知</a></li>");	
document.writeln("					<li value=\"8\"><a href=\"javascript:void(0)\" onclick=\"checkIt(this);\">本校课程</a></li>");	
document.writeln("					<li value=\"3\"><a href=\"javascript:void(0)\" onclick=\"checkIt(this);\" class=\"Lastli\">全国课程</a></li>");	
document.writeln("				</ul>");	
document.writeln("			</strong>");	
document.writeln("			<input type=\"text\" id=\"searchKey\" name=\"searchKey\" style=\"width: 190px;margin-left: 7px;\" placeholder=\"请输入课程名称\"/>");	
document.writeln("			<a href=\"javascript:;\" onclick=\"searchAll(\'sx.cnu.edu.cn\');\"><img src=\"http://sx.cnu.edu.cn/portal/sdsfdx/images/ss.png\" /></a>");	
document.writeln("			<input type=\"hidden\" id=\"searchTypeInp\"  value=\"8\" />");	
document.writeln("        	  <form action=\"\" method=\"get\" id=\"searchAllFrom\">");	
document.writeln("        		<input name=\"pageNum\" value=\"1\" type=\"hidden\" id=\"pageNum\" />");	
document.writeln("        		<div id=\"putData\"></div>");	
document.writeln("        	  </form>");	
document.writeln("		</div>");	
document.writeln("	</div>");	
document.writeln("</div>");	
document.writeln("<!--banner开始-->");	
document.writeln("<div class=\"banner\">");	
document.writeln("	<div id=\"full-screen-slider\">");	
document.writeln("		<ul id=\"slides\">");	
document.writeln("						<li style=\"background:url(\'https://p.ananas.chaoxing.com/star3/1920_352c/41ea4eb8ef8217bd11c405f5b1ad635d.png\') no-repeat center top\">");	
document.writeln("				<a   href=\"http://www.icourse163.org/course/CNU-1001600006\" target=\"_blank\" >教学权威资源库</a>");	
document.writeln("			</li>");	
document.writeln("						<li style=\"background:url(\'https://p.ananas.chaoxing.com/star3/1920_352c/c089a2750635554be777a6f203ec783c.png\') no-repeat center top\">");	
document.writeln("				<a >教学权威资源库</a>");	
document.writeln("			</li>");	
document.writeln("					</ul>");	
document.writeln("	</div>");	
document.writeln("</div>");	
document.writeln("<div class=\"Nav\">");	
document.writeln("	<div class=\"Wid1000\">");	
document.writeln("	<ul>");	
document.writeln("		    		    		    		<li  class=\"licur\" >");	
document.writeln("    			    				<a  href=\"http://sx.cnu.edu.cn/portal\">首页</a>");	
document.writeln("								|");	
document.writeln("				            </li>");	
document.writeln("    	    		    		<li >");	
document.writeln("    			    				<a  target=\"_blank\"  href=\"http://sx.cnu.edu.cn/portal/schoolCourseInfo/columnCourse?columnId=16626\">MOOC</a>");	
document.writeln("								|");	
document.writeln("				            </li>");	
document.writeln("    	    		    		<li >");	
document.writeln("    			    				<a  href=\"http://sx.cnu.edu.cn/portal/schoolonlinecourse/index\">校内在线课程</a>");	
document.writeln("								|");	
document.writeln("				            </li>");	
document.writeln("    	    		    		<li >");	
document.writeln("    			    				<a  href=\"http://sx.cnu.edu.cn/study/resource\">资源中心</a>");	
document.writeln("								|");	
document.writeln("				            </li>");	
document.writeln("    		</ul>");	
document.writeln("	</div>");	
document.writeln("</div>");	
document.writeln("<script type=\"text/javascript\">");	
document.writeln("    function goPassport2Login() {");	
document.writeln("		    	            	location.href = \"http://sx.cnu.edu.cn/login/cnu\";");	
document.writeln("    }");	
document.writeln("    function goRegister() {");	
document.writeln("    	location.href = \"http://passport2.chaoxing.com/register/student?fid=408&refer=http://sx.cnu.edu.cn\";");	
document.writeln("    }");	
document.writeln("$(document).ready(function() {");	
document.writeln("    $(\'.Nav li\').hover(function(){");	
document.writeln("		$(this).find(\'.n_bottm\').slideDown(100);");	
document.writeln("	},function(){");	
document.writeln("		$(this).find(\'.n_bottm\').slideUp(100);");	
document.writeln("	})");	
document.writeln("});");	
document.writeln("</script>");	
